stages:
  - test
  - deploy

default:
  image: gradle:jdk17-corretto
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle_home
    - echo "bhmNexusUsername=$NEXUS_SERVICE_USERNAME\n" >> gradle.properties
    - echo "bhmNexusPassword=$NEXUS_SERVICE_PASSWORD\n" >> gradle.properties
  cache:
    - key: dep-cache
      paths:
        - .gradle_home

test:
  stage: test
  script:
    - ./gradlew clean test --build-cache

deploy:
  stage: deploy
  script:
    - ./gradlew publish